# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Mar  7 01:19:37 2010

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class ListFrame(wx.MDIChildFrame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ListFrame.__init__
        kwds["style"] = wx.FRAME_TOOL_WINDOW|wx.CLIP_CHILDREN
        wx.MDIChildFrame.__init__(self, *args, **kwds)
        self.sizer_13_staticbox = wx.StaticBox(self, -1, "Lista")
        self.list_box_1 = wx.ListBox(self, -1, choices=["FINIT", "FFREE", "FLD", "FCOM", "FXCH", "FADDP", "FSUBP", "FYL2X", "FSINCOS", "FSQRT"], style=wx.LB_MULTIPLE)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ListFrame.__set_properties
        self.SetTitle("Lista")
        self.list_box_1.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ListFrame.__do_layout
        sizer_13 = wx.StaticBoxSizer(self.sizer_13_staticbox, wx.HORIZONTAL)
        sizer_13.Add(self.list_box_1, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_13)
        sizer_13.Fit(self)
        self.Layout()
        # end wxGlade

# end of class ListFrame


