# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Mar  6 02:31:35 2010

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.sizer_12_staticbox = wx.StaticBox(self, -1, "Pila")
        self.sizer_7_staticbox = wx.StaticBox(self, -1, "Registro de Control")
        self.sizer_8_staticbox = wx.StaticBox(self, -1, "Registro de Estado")
        self.sizer_3_staticbox = wx.StaticBox(self, -1, "Instrucciones")
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "Nuevo", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "Abrir", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "Guardar", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.NewId(), "Guardar como...", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.NewId(), "Salir", "", wx.ITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "Archivo")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), u"Índice", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.NewId(), "Acerca de..", "", wx.ITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "Ayuda")
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.statusbar = self.CreateStatusBar(2, 0)
        
        # Tool Bar
        self.frame_1_toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL|wx.TB_DOCKABLE)
        self.SetToolBar(self.frame_1_toolbar)
        self.frame_1_toolbar.AddLabelTool(wx.NewId(), "Nuevo", wx.Bitmap("icons/document-new.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_1_toolbar.AddLabelTool(wx.NewId(), "Abrir", wx.Bitmap("icons/document-open.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_1_toolbar.AddLabelTool(wx.NewId(), "Guardar", wx.Bitmap("icons/document-save.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_1_toolbar.AddLabelTool(wx.NewId(), "Guardar como...", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_1_toolbar.AddSeparator()
        self.frame_1_toolbar.AddLabelTool(wx.NewId(), "Arriba", wx.Bitmap("icons/go-top.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_1_toolbar.AddLabelTool(wx.NewId(), "Subir", wx.Bitmap("icons/go-up.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_1_toolbar.AddLabelTool(wx.NewId(), "Bajar", wx.Bitmap("icons/go-down.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_1_toolbar.AddLabelTool(wx.NewId(), "Abajo", wx.Bitmap("icons/go-bottom.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_1_toolbar.AddLabelTool(wx.NewId(), "Borrar", wx.Bitmap("icons/list-remove.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_1_toolbar.AddSeparator()
        self.frame_1_toolbar.AddLabelTool(wx.NewId(), "Ejecutar", wx.Bitmap("icons/go-next.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        # Tool Bar end
        self.instructionInput = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER|wx.TE_PROCESS_TAB)
        self.bitmap_button_1 = wx.BitmapButton(self, -1, wx.Bitmap("icons/list-add.png", wx.BITMAP_TYPE_ANY))
        self.instructionsList = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.LC_EDIT_LABELS|wx.LC_HRULES|wx.SUNKEN_BORDER)
        self.stackList = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.controlList = wx.ListCtrl(self, -1, style=wx.LC_LIST|wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.statusList = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.actionNew, id=-1)
        self.Bind(wx.EVT_MENU, self.actionOpen, id=-1)
        self.Bind(wx.EVT_MENU, self.actionSave, id=-1)
        self.Bind(wx.EVT_MENU, self.actionSaveAs, id=-1)
        self.Bind(wx.EVT_MENU, self.actionExit, id=-1)
        self.Bind(wx.EVT_MENU, self.actionShowHelp, id=-1)
        self.Bind(wx.EVT_MENU, self.actionShowAbout, id=-1)
        self.Bind(wx.EVT_TOOL, self.actionOpen, id=-1)
        self.Bind(wx.EVT_TOOL, self.actionSave, id=-1)
        self.Bind(wx.EVT_TOOL, self.actionSaveAs, id=-1)
        self.Bind(wx.EVT_TOOL, self.actionGoTop, id=-1)
        self.Bind(wx.EVT_TOOL, self.actionDown, id=-1)
        self.Bind(wx.EVT_TOOL, self.actionBottom, id=-1)
        self.Bind(wx.EVT_TOOL, self.actionDelete, id=-1)
        self.Bind(wx.EVT_TOOL, self.actionRunNext, id=-1)
        self.Bind(wx.EVT_TEXT_ENTER, self.addInstruction, self.instructionInput)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("FPU Inspector")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("icons/icon.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.statusbar.SetStatusWidths([300, -1])
        # statusbar fields
        statusbar_fields = [u"Agregue una instrucción para comenzar", ""]
        for i in range(len(statusbar_fields)):
            self.statusbar.SetStatusText(statusbar_fields[i], i)
        self.frame_1_toolbar.Realize()
        self.instructionInput.SetMinSize((200, 27))
        self.instructionInput.SetToolTipString(u"Ingrese una instrucción de FPU aquí")
        self.instructionInput.SetFocus()
        self.bitmap_button_1.SetSize(self.bitmap_button_1.GetBestSize())
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.StaticBoxSizer(self.sizer_8_staticbox, wx.HORIZONTAL)
        sizer_7 = wx.StaticBoxSizer(self.sizer_7_staticbox, wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.StaticBoxSizer(self.sizer_12_staticbox, wx.HORIZONTAL)
        sizer_3 = wx.StaticBoxSizer(self.sizer_3_staticbox, wx.VERTICAL)
        sizer_4 = wx.FlexGridSizer(1, 2, 0, 0)
        sizer_4.Add(self.instructionInput, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add(self.bitmap_button_1, 0, 0, 0)
        sizer_3.Add(sizer_4, 0, wx.EXPAND, 0)
        sizer_3.Add(self.instructionsList, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_12.Add(self.stackList, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_12, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_7.Add(self.controlList, 1, wx.EXPAND|wx.FIXED_MINSIZE, 0)
        sizer_6.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_8.Add(self.statusList, 1, wx.EXPAND|wx.FIXED_MINSIZE, 0)
        sizer_6.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_6, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def actionNew(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `actionNew' not implemented!"
        event.Skip()

    def actionOpen(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `actionOpen' not implemented!"
        event.Skip()

    def actionSave(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `actionSave' not implemented!"
        event.Skip()

    def actionSaveAs(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `actionSaveAs' not implemented!"
        event.Skip()

    def actionExit(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `actionExit' not implemented!"
        event.Skip()

    def actionShowHelp(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `actionShowHelp' not implemented!"
        event.Skip()

    def actionShowAbout(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `actionShowAbout' not implemented!"
        event.Skip()

    def actionGoTop(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `actionGoTop' not implemented!"
        event.Skip()

    def actionDown(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `actionDown' not implemented!"
        event.Skip()

    def actionBottom(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `actionBottom' not implemented!"
        event.Skip()

    def actionDelete(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `actionDelete' not implemented!"
        event.Skip()

    def actionRunNext(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `actionRunNext' not implemented!"
        event.Skip()

    def addInstruction(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `addInstruction' not implemented!"
        event.Skip()

# end of class MainFrame


