#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Mar 16 15:35:25 2010

import wx
from MyFrame import MyFrame

class main():
    def __init__(self):
        self.app = wx.PySimpleApp(0)
        wx.InitAllImageHandlers()
        self.frame_1 = MyFrame(None, -1, "")
        self.app.SetTopWindow(self.frame_1)
        self.frame_1.Show()
        self.app.MainLoop()


if __name__ == "__main__":
    main()
