# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Mar 16 15:35:25 2010

import wx

from wrapper import Wrapper

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)


        self.lib = Wrapper()

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

       


    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.text_ctrl_1.SetMinSize((300,200))
        # end wxGlade
        self.refresh()


    def refresh(self):
        pila = self.lib.get_stack()
        for item in pila:
            #self.text_ctrl_1.Clear()
            self.text_ctrl_1.WriteText(u'%s\n' % unicode(item))



    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.text_ctrl_1, 0, wx.ALL|wx.EXPAND, 3)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame


