# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Mar 17 16:39:07 2010

import wx
from multiprocessing.managers import BaseManager

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

from wrapper import Wrapper

class MyManager(BaseManager):
    pass

MyManager.register('Wrapper', Wrapper)



class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY)
        self.text_ctrl_2 = wx.TextCtrl(self, -1, "")
        self.button_add = wx.Button(self, -1, "FLD")
        self.button_refresh = wx.Button(self, -1, "Refresh")


        self.manager = MyManager()
        self.manager.start()        
        self.lib = self.manager.Wrapper()

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

        self.refresh(None)

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.text_ctrl_1.SetMinSize((300,200))
        # end wxGlade
        
        self.Bind(wx.EVT_BUTTON, self.refresh, self.button_refresh)
        self.Bind(wx.EVT_BUTTON, self.add, self.button_add)
        
        

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.text_ctrl_1, 0, wx.ALL|wx.EXPAND, 3)
        sizer_4.Add(self.text_ctrl_2, 0, wx.ALL, 3)
        sizer_4.Add(self.button_add, 0, wx.ALL, 3)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_3.Add(self.button_refresh, 0, wx.ALL, 3)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade


    def refresh(self, event):
        pila = self.lib.get_stack()
        for item in pila:
            #self.text_ctrl_1.Clear()
            self.text_ctrl_1.WriteText(u'%s\n' % unicode(item))
        self.text_ctrl_1.WriteText('-' * 20)


    def add(self, event):
        number = float(self.text_ctrl_2.GetValue())
        self.lib.FLD(number)

# end of class MyFrame


